In [12]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(torch.__version__)

2.3.1+cpu


In [16]:
# scalar
x = torch.tensor(7)
print(x)
print(x.ndim)
print(x.item())

tensor(7)
0
7


In [2]:
a = [1,2,3,5]
a

[1, 2, 3, 5]

Tensors

In [3]:
tensor_2d= torch.randn(3,4)
tensor_2d

tensor([[ 0.4808, -0.9913,  0.3170, -0.0063],
        [ 0.4587, -0.5552, -0.4796,  0.1292],
        [ 1.3621,  0.3759, -1.3948,  0.3692]])

In [6]:
tensor_2d= torch.zeros(3,4)
tensor_2d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# creating tensors from numpy arrays
b = torch.tensor(a)
b

tensor([1, 2, 3, 5])

In [17]:
# vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [22]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor

tensor([[[0.4086, 0.2953, 0.3341],
         [0.7058, 0.3661, 0.6530],
         [0.6636, 0.8969, 0.7904],
         ...,
         [0.8902, 0.7542, 0.4104],
         [0.7963, 0.1129, 0.5641],
         [0.6669, 0.5105, 0.9382]],

        [[0.3252, 0.1569, 0.6330],
         [0.7486, 0.5133, 0.8483],
         [0.4513, 0.2232, 0.4559],
         ...,
         [0.1277, 0.4772, 0.5216],
         [0.5175, 0.6487, 0.1264],
         [0.8587, 0.3447, 0.8630]],

        [[0.5546, 0.7125, 0.3138],
         [0.0752, 0.6037, 0.4562],
         [0.7522, 0.9475, 0.9130],
         ...,
         [0.4647, 0.3471, 0.3723],
         [0.9396, 0.3794, 0.4073],
         [0.7170, 0.6313, 0.6143]],

        ...,

        [[0.7631, 0.5028, 0.8157],
         [0.1121, 0.6952, 0.1965],
         [0.4359, 0.8302, 0.1963],
         ...,
         [0.1756, 0.8875, 0.3761],
         [0.3078, 0.1167, 0.7263],
         [0.9079, 0.0243, 0.2588]],

        [[0.1927, 0.1513, 0.3539],
         [0.5789, 0.1760, 0.8982],
         [0.

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = torch.rand(3,4)
a

tensor([[0.0463, 0.0166, 0.5331, 0.5002],
        [0.4878, 0.1442, 0.6112, 0.1847],
        [0.0509, 0.4468, 0.9070, 0.9975]])

In [29]:
b = torch.rand(4,3)
b

tensor([[0.4170, 0.6922, 0.2191],
        [0.8475, 0.0631, 0.0738],
        [0.9589, 0.6514, 0.8666],
        [0.1609, 0.1630, 0.0217]])

In [30]:
torch.matmul(a,b)

tensor([[0.6251, 0.4619, 0.4842],
        [0.9415, 0.7750, 0.6512],
        [1.4302, 0.8169, 0.8518]])

In [35]:
a@b 
# @ = matmul


tensor([[0.6251, 0.4619, 0.4842],
        [0.9415, 0.7750, 0.6512],
        [1.4302, 0.8169, 0.8518]])

In [36]:
torch.mm(a,b)

tensor([[0.6251, 0.4619, 0.4842],
        [0.9415, 0.7750, 0.6512],
        [1.4302, 0.8169, 0.8518]])

In [38]:
print(a.max())
print(torch.max(a))

tensor(0.9975)
tensor(0.9975)


In [39]:
print(a.min())
print(torch.min(a))

tensor(0.0166)
tensor(0.0166)


In [40]:
print(a.argmax())
print(torch.argmax(a))

tensor(11)
tensor(11)


In [41]:
print(a.argmin())
print(torch.argmin(a))

tensor(1)
tensor(1)


In [47]:
c = torch.arange(3,10)
c

tensor([3, 4, 5, 6, 7, 8, 9])

In [48]:
c_stacked  = torch.stack([c,c,c,c],dim = 0)
c_stacked

tensor([[3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 8, 9]])

In [51]:
c_stacked.squeeze()

tensor([[3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 8, 9]])

In [52]:
# indexing (selecting data from tensors)
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
x[0,0],x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [56]:
x[0,0,0] , x[0][0][0]

(tensor(1), tensor(1))

In [60]:
# numpy array to tensor
array = np.arange(1,10)
tensor = torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [61]:
array = array+1
array,tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [62]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# reproducibility (tryng to take random out of random)


In [64]:
a = torch.rand(3,4)
b = torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.6023, 0.0959, 0.6370, 0.2396],
        [0.1523, 0.1930, 0.6008, 0.1354],
        [0.9245, 0.8734, 0.6374, 0.2410]])
tensor([[0.9790, 0.2206, 0.6998, 0.6573],
        [0.8715, 0.7162, 0.2396, 0.8947],
        [0.2817, 0.7267, 0.2323, 0.3263]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [68]:
random_seed = 42
torch.manual_seed(random_seed)
c = torch.rand(3,4)
torch.manual_seed(random_seed)
d = torch.rand(3,4)
print(c)
print(d)
print(c==d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [70]:
torch.cuda.is_available()

False